"""empty message

Revision ID: a20a6cd038c0
Revises: f469d8856941
Create Date: 2024-12-10 16:34:14.403060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a20a6cd038c0'
down_revision = 'f469d8856941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('host_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databases')
    # ### end Alembic commands ###
